import './globals.css'; // Projenin global stil dosyasını içe aktarıyor
import type { Metadata } from 'next'; // Next.js'in Metadata türünü içe aktarıyor
import { Inter } from 'next/font/google'; // Google'dan "Inter" fontunu içe aktarıyor

// "Inter" yazı tipi ayarlarını yapılandırıyor, burada Latin alfabesi destekleniyor
const inter = Inter({ subsets: ['latin'] });

// Sayfa meta bilgileri, bu bilgiler tarayıcı sekmesi ve arama motorları için kullanılır
export const metadata: Metadata = {
  title: 'Create Next App', // Sayfa başlığı
  description: 'Generated by create next app', // Sayfa açıklaması
};

// RootLayout bileşeni, tüm uygulama için ortak bir düzen sağlar
export default function RootLayout({
                                     children, // Bileşenin içine yerleştirilecek tüm alt bileşenler
                                   }: {
  children: React.ReactNode; // "React.ReactNode" tipi, herhangi bir React bileşenini temsil eder
}) {
  return (
      <html lang="en"> {/* HTML dilini İngilizce olarak belirliyor */}
      <body className={inter.className}>
      {/* Google'dan gelen "Inter" fontu tüm body'ye uygulanıyor */}
      {children} {/* Bu, diğer bileşenlerin bu düzen içine yerleştirileceği yerdir */}
      </body>
      </html>
  );
}
